# Generated by Django 4.1.3 on 2023-01-26 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('woman', 'woman'), ('man', 'man'), ('traveler', 'traveler'), ('transgender woman', 'transgender woman'), ('transgender man', 'transgender man'), ('non-binary', 'non-binary'), ('agender', 'agender')], max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_img', models.ImageField(blank=True, default='user_profile_images/default-user-image.png', upload_to='user_profile_images/')),
                ('countries_visited', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('adventure_level', models.CharField(choices=[('Travel Enthusiast', 'Travel Enthusiast'), ('Adventurer', 'Adventurer'), ('Globetrotter', 'Globetrotter')], default='Travel Enthusiast', max_length=150)),
            ],
        ),
    ]
